export const ATTRIBUTE = {
    FIRST_EDITION: '1E',
    SECOND_EDITION: '2E',
    SPELL: 'Spell',
    RACE: 'Race',
    CLASS: 'Class',
    WEAPON: 'Weapon',

    TURN_UNDEAD: 'Turn Undead',
    INVISIBILITY: 'Invisibility',
    BLINDNESS: 'Blindness',
    DEAFNESS: 'Deafness',
    SILENCE: 'Silence',
    DISPEL_MAGIC: 'Dispel Magic',
    STONESKIN: "Stoneskin",
    MAGICAL_AGING: "Magical aging",
    DOT: "Continuing Damage",
    ELVEN_RESISTANCE: "Elven resistance",
    GNOME_BASTARD_SWORD: "Gnome Bastard sword",
    RANGED_IN_MELEE: "Ranged in melee",
    MONSTER_ABILITY_SCORES: "Monster Ability Scores",
    INTELLIGENCE_VS_ILLUSIONS: "Int vs illusion",
    PANTHEON: "Pantheon",
    MAGIC_ITEM_SIZE: "Magic item size",
    SCROLL: "Scroll",
    MORNING_STAR: "Morningstar",
    D30: "d30",
    BOWS_AND_STRENGTH: "Bows and Strength",
    PRONOUNCE_DROW: 'Pronounce drow',
    PRONOUNCE_FLIND: 'Pronounce flind',

    APRIL_FOOLS: 'April Fools',
};

const ATTRIBUTES = [
    {id: ATTRIBUTE.FIRST_EDITION},
    {id: ATTRIBUTE.SECOND_EDITION},
    {id: ATTRIBUTE.SPELL},
    {id: ATTRIBUTE.CLASS},
    {id: ATTRIBUTE.ELVEN_RESISTANCE, title: "Elven resistance to Sleep and Charm"},
    {id: ATTRIBUTE.GNOME_BASTARD_SWORD, title: "Gnomes with Bastard sword"},
    {id: ATTRIBUTE.RANGED_IN_MELEE, title: "Ranged weapons in melee combat"},
    {id: ATTRIBUTE.BOWS_AND_STRENGTH, title: "Bows and Strength bonus"},
    {id: ATTRIBUTE.MORNING_STAR, title: "What is a morning star?"},
    {id: ATTRIBUTE.INTELLIGENCE_VS_ILLUSIONS, title: "High Intelligence illusion immunity"},
    {id: ATTRIBUTE.D30, title: "What comes after a d20?"},
    {id: ATTRIBUTE.SCROLL, title: "Scroll rules and limitations"},
    {id: ATTRIBUTE.MAGIC_ITEM_SIZE, title: "Who fit magic items?"},
    {id: ATTRIBUTE.PANTHEON, title: "Pantheon of the Month"},
    {id: ATTRIBUTE.DISPEL_MAGIC},
    {id: ATTRIBUTE.TURN_UNDEAD},
    {id: ATTRIBUTE.INVISIBILITY},
    {id: ATTRIBUTE.BLINDNESS},
    {id: ATTRIBUTE.DEAFNESS},
    {id: ATTRIBUTE.SILENCE},
    {id: ATTRIBUTE.STONESKIN},
    {id: ATTRIBUTE.DOT},
    {id: ATTRIBUTE.MAGICAL_AGING},
    {id: ATTRIBUTE.PRONOUNCE_DROW, title: 'How to pronouncing "drow"'},
    {id: ATTRIBUTE.PRONOUNCE_FLIND, title: 'How to pronouncing "flind"'},
    {id: ATTRIBUTE.APRIL_FOOLS},
];

// module.exports = ATTRIBUTES;